### ISSUE TITLE
Add new manager

### ISSUE THREAD

**Issue by TheBearodactyl** [TeFiLeDo/fish-autoupdate-plugin#1]
Please add omf :D

**Comment by TeFiLeDo** [comment]
Sorry it took so long. I overlooked your request and only noticed it today when searching for an old email.

I added support for omf in [v0.4](https://github.com/TeFiLeDo/fish-autoupdate-plugin/releases/tag/v0.4). Don't forget to set the package manager, as `fisher` still is the default.

**Comment by TheBearodactyl** [comment]
thanks :D
